<div class="container p-3">
    <h3>Kowal:</h3>
    <h6>Twoja waluta: <?php echo $user['coins']; ?></h6>

    <div class="row">
        <table class="table table-striped col-md-5">
            <thead>
                <tr>
                    <th>Nazwa</th>
                    <th>Jakość</th>
                    <th>Cena</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    require_once __DIR__ . '\..\helpers/weapon.php';
                    require_once __DIR__ . '\..\helpers/user.php';
                    $user = User::getAllInfo();
                    $weapons = json_decode($user['weapons']);
                    for ($i = 0; $i < count($weapons); $i++) {
                        $weapon = $weapons[$i];
                        echo '<tr>
                            <td>' . $weapon->typeOfWeapon . ' ' . $weapon->name . '</td>
                            <td>' . $weapon->HTMLQuality . '</td>
                            <td class="text-center"><a class="btn-link" href="buy/weapon/' . $weapon->id . '">$' . $weapon->value . '</a></td>
                        </tr>';
                    }
                ?>
            </tbody>
        </table>
        <div class="col-md-2">
        </div>
        <table class="table table-striped col-md-5">
            <thead>
                <tr>
                    <th>Nazwa</th>
                    <th>Jakość</th>
                    <th>Cena</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    require_once __DIR__ . '\..\helpers/armor.php';
                    require_once __DIR__ . '\..\helpers/user.php';
                    $user = User::getAllInfo();
                    $armors = json_decode($user['armors']);
                    for ($i = 0; $i < count($armors); $i++) {
                        $armor = $armors[$i];
                        echo '<tr>
                            <td>' . $armor->typeOfArmor . ' ' . $armor->name . '</td>
                            <td>' . $armor->HTMLQuality . '</td>
                            <td class="text-center"><a class="btn-link" href="buy/armor/' . $armor->id . '">$' . $armor->value . '</a></td>
                        </tr>';
                    }
                ?>
            </tbody>
        </table>
    </div>

</div>